@startuml
skinparam style strictuml

package "Data Layer " {
  class Student {
    + id : Long
    + firstName : String
    + lastName : String
  }

  class Grade {
    + id : Long
    + grade : int (1 to 6)
    + studentId : Long
  }

}

Grade --> Student : "belongs to"
@enduml