@startuml
skinparam style strictuml

package "Data Layer" {
  class Student {
    + id : Long
    + firstName : String
    + lastName : String
    + email : String
  }

  class Grade {
    + id : Long
    + value : int (1 to 6)
    + subject : String
    + studentId : Long
  }

}

Grade --> Student : "belongs to"
@enduml